### ISSUE TITLE
Example usage of ONNX in project documentation

### ISSUE THREAD

**Issue by mominggame** [gidesa/ocvWrapper46#10]
Hello, I was exploring the project's documentation and I noticed that there isn't a clear example of how to use ONNX in the project. I think it would be helpful to have a tutorial or code example that demonstrates how to incorporate ONNX into the project's workflow. ONNX is a popular format for representing deep learning models, and I believe it would be valuable to show users how to use it in the context of this project. Would it be possible to add such an example to the documentation? Thank you for your time and consideration.

**Comment by gidesa** [comment]
Hello, I don't exactly understand what you are writing about ONNX. The face detector and recognizer just show how to load a ONNX DNN network, and how to feed the DNN net with image. 
But, independently from the disk format (ONNX or another), every DNN network is different from another, often in feeding the input, and always in interpreting the output results.
