### ISSUE TITLE
Error installing component

### ISSUE THREAD

**Issue by AlexKid777** [gidesa/ocvWrapper46#11]
I'm trying to install the test components in Delphi 11 and it's giving me an error during installation, the compilation passes without any problems. I put the following DLLs in the source folder of the pkocvWrapComp project:

ocvCPPWrapper46.dll
opencv_videoio_ffmpeg460.dll
opencv_world460.dll
opencv_world460d.dll

All in 32bit versions, the error that is giving is:

The specified module could not be found.

**Comment by gidesa** [comment]
To load these components, the Delphi 11 IDE requires to find the 64 bit DLLs (wrapper and Opencv) in the path. 
Other older IDE (as XE2) are 32 bit, and require corresponding DLLs in path.

**Comment by AlexKid777** [comment]
So does this mean that in Delphi 11 I can only use the components if my project is compiled for 64bits, or can I install the components and then use them in a 32bits project?

**Comment by gidesa** [comment]
The 64 bit DLL are required just to use components in IDE. Then you can develop 32 or 64 bit; but, when debugging, the program exe has to find the correct DLLs. For example you can set a different path in menù Run/Parameters/Environment block.
Think that, indeed, the wrapper DLL for 32 bit has a different name than the one for 64 bit. But unluckily the Opencv DLL have the same name for 32 and 64.
