### ISSUE TITLE
Delphi or Lazarus integration

### ISSUE THREAD

**Issue by xecroint** [gidesa/ocvWrapper46#13]
I can't tell you how happy I was about the co-implimentation for lazarus. **Thank you so much !**
The installation on Windows x64 was not without problems, but after I downloaded the appropriate 64bit dll's and copied them into the installation directory, everything was smooth.
A big problem I personally have is the interaction with Delphi respectively Lazarus. All examples show more or less raw functionality of openCV in its own framework.
For example: here the image is shown as a function of openCV in a new openCV-window:
    cvstr.pstr:=PAnsiChar(AnsiString('result'));
    pCvimshow(@cvstr, img1);
but how can one pass bitmaps from VLC / LCL to openCV and how to show the results in VLC / LCL bitmaps after processing ?
More examples about the interaction of the wrapper with Delphi or Lazarus would be very helpful …

Thanks a million !

**Comment by havezet** [comment]
I am a rookie user of this repository myself, but you can create a TBitmap from a mat image. Not sure if that's the easiest way.

1. use the unit unOpencvDelphi46
2. create a TOCVImage, which has a constructor with a PCvMat_t parameter
3. call the TOCVImage instance its toBmp method.

**Comment by xecroint** [comment]
Thanks a lot for your fast reply!
The unit unOpencvDelphi46 I already have in use. I now tried two days just to manage that openCV accesses the internal bitmaps and I'm afraid that this exceeds my knowledge ... I'm tired of seeing the debugger window popping up …
I better stick with my Python script and forget the idea to implement that in Lazarus directly. Thank you anyway (-;

**Comment by gidesa** [comment]
Hello, thank you for appreciating my work.
I copy here the answer to same question by havezet:
You could load a Opencv image from a TBitmap object, using the Bitmap2MatImage function in OpenCvWrapper.pas.
This, because the internal memory of a Opencv image is very similar to a bitmap image.
If you use the TOcvImage class from unOpencvDelphi46.pas (an abstraction over a Opencv Mat image), there are methods to convert to/from TBitmap: toBmp/fromBmp, simply they encapsulate the Bitmap2MatImage/Matimage2Bitmap functions.
An example of use could be the ShowInimage method of TOCVImage class:

procedure TOCVImage.showInImage(formImg: TImage);
var
  rec: TRect;
  bmp: TBitmap;
  colorImg: PCvMat_t;
begin
    bmp := TBitmap.Create;
    bmp.PixelFormat :=  pf24bit;
    resetROI;
    if fNchannels=1 then
    begin
      colorImg:=pCvMatImageCreate(fWidth, fHeight,  CV_8UC3);
      pCvCvtColor(internImage, colorImg, Ord(COLOR_GRAY2BGR));
      MatImage2Bitmap(colorImg, bmp);
      pCvMatDelete(colorImg);
    end
    else
    begin
      MatImage2Bitmap(internImage, bmp);
    end;
    rec := formImg.canvas.ClipRect;
    formImg.canvas.StretchDraw(rec , bmp);
    bmp.Free;
    setROI(fROI);
end;

In this case the Opencv Mat image is converted to a bmp, then copied to a TImage canvas bitmap.
NOTE: conversion routines require always a 3 color channels image, so if the Mat is 1 channel then it's converted to 3 channels.
So, in my opinion, the interaction between Delphi/Lazarus graphic with Opencv images is very simple and straight.
But you are right, a specific example could be very useful.
I will add in next days.

**Comment by xecroint** [comment]
I really apologize. I've been trying to get
pCvminMaxLoc(result, @minVal, @maxVal, @minLoc, @maxLoc, nil);
to work, but whatever I try, since two days, to initialize those minVal and minLoc values, the application crashes  it's so unbelievable exhausting. You do not have an example of how to use this essential function for MatchTemplate with Delhi or Lazarus the right way ?
Thanks !

**Comment by gidesa** [comment]
You can see the MidasDNN example, in frmmidasdnn.pas there is a line with pCvMinMaxLoc. In your code verify that all the pointers are valid.

**Comment by xecroint** [comment]
Thanks for the advice. I tried that one and it passes through without rising an exception but this is just half of the rent as I still did not manage to get it running with locMin and locMax.
I finally gave it up and this is not due to your implementation (!) it is because with just a wrapper, everything is a hassle ...
- everything is trial and error.
- even if the compiler does not complain, the interaction between the source and dll rises exceptions during runtime.
- there's no real documentation to walk through and to find out what exactly could cause the issue.
- and finally (!) and that is the main reason for me right now: the interaction between Lazarus and openCV is a pure pain in the ass. With your help, we successfully solved to share bitmaps, but when it comes to access and convert openCV variables from Lazarus it appears to be a dead end or -at least- requires lots of trial and error and this is exhausting and frustrating.
As long as no code exists, that shows how both languages can interact on both, images and results, one can also run a python script without all this headache ...
Thanks a lot for your help, really appreiated, but after 40+ hours of investigation and frustration I better continue with Python and implement a TProcess-Pipe comminucation between both.

**Comment by gidesa** [comment]
Regarding min/max location, I have tried this code fragment in Lazarus:
var
  minloc, maxloc: PCvPoint_t;
  pts1, pts2: CvPointS;

.........

    minloc:=CvPoint_(0,0);
    maxloc:=CvPoint_(0,0);

    pCvminMaxLoc(heatMap, @vMin, @vMax, minloc, maxloc );
    pCvPointToStruct(minloc, @pts1);
    pCvPointToStruct(maxloc, @pts2);

No errors/exceptions, in struct pts I see valid values, first for minloc, and after for maxloc .
Remember to release  Opencv memory when finished to use minloc and maxloc:

    pCvPointDelete(minloc);
    pCvPointDelete(maxloc);

Maybe you have passed @minloc and @maxloc, instead they are just pointers and not require @ operator. I have done this error, obtaining an exception.
I appreciate Python, a nice interpreted language. But it's many times slower than compiled Pascal, personally I develop software that require a quasi-realtime execution. So Python is no choice. 
A big problem with this converter is that it just convert C++ classes to plain functions. So in Pascal you have to remember to create (and destroy) the appropriate Ocv class (with functions pCvxxxcreate and pCvxxxdelete) before  calling Ocv functions.
Regarding the docs, of course this is my voluntary project, I agree that it lack "professional smoothness".

**Comment by xecroint** [comment]
I really appreciate your help a lot.
And in my opinion, the lack of smootheness is not an issue because of the documentation. It's the nature of a wrapper to DLLs that have been compiled with a completely different structure ...  Of course, for my personal use, those examples could focus more on the implementation specific issues and the language (delphi, Lazarus) specific approach and rather than on openCV image processing (-;

With regards to Python: I don't think, that there's a huge difference in speed. Depending on the application one needs to solve, most of the time is used by openCV itself and not by it's overlay.

With regards to the pCvminMaxLoc() example you kindly provided. It functions well, now since I applied your changes. I simply did not expect that I have to initialize minLoc and maxLoc by assigning a CvPoint to them. In my understanding, declaration of a variable (minloc, maxloc: PCvPoint_t;)  is sufficient – as I wrote: it's a hassle.

Btw: now, since I went one step closer ... I miss the function »pCvwarpAffine«. Has it been implemented ?

**Comment by gidesa** [comment]
It's true that a comprensive doc is lacking, but Readme deserves to be read, isn't? ;-) Here you find some basic concepts. One of  them is that many, if not all, Opencv variables are classes instances. So you have to create, use, and at end delete them, as every object in Pascal. No difference.
Another needed doc is the Opencv one, of course: 
   https://docs.opencv.org/4.6.0/
Regarding warpAffine, the signature is:
    Procedure  pCvwarpAffine(src: PCvMat_t; dst: PCvMat_t; M: PCvMat_t; dsize: PCvSize_t; 
                 flags: Integer { default: INTER_LINEAR } = ord(INTER_LINEAR); borderMode: Integer { default: BORDER_CONSTANT } =     ord(BORDER_CONSTANT);   borderValue: PCvScalar_t { default: Scalar() } = nil);
Mandatory input are a source Mat (image); a destination one, a different image; a transformation matrix M, again a Mat object for Opencv; a CvSize object with the size of output image w x h. Other parameters have defaults.
CvMat, CvSize, CvScalar are all classes, so first must be created, directly from you or from some Opencv function/method.
