### ISSUE TITLE
Differences from “dnnObjectDetection” darknet training results

### ISSUE THREAD

**Issue by hechoel** [gidesa/ocvWrapper46#19]
hello

I am trying to use the yolov4 weights file learned with darknet, but the learning results from darknet are different from the results detected by the “dnnObjectDetection” sample program.

I tried modifying the image size and Threshold Value global variables, but they are still the same.
(The image size in the "dnnObjectDetection" sample program is 416, so it has been changed to 416 and re-training is in progress...)

Do you know the solution?

**Comment by gidesa** [comment]
The example program dnnObjectDetection is translated from C++ sources from Opencv distribution, and use yolo3 weights trained   with images of size 416x416, as you has just noted.
  W_IN: integer =  416;
  H_IN: Integer =  416;

You can simply change the parameters to whatever size have used in training.
What is the other program that you compare the objects list results?

**Comment by hechoel** [comment]
It is a program called darknet that trains yolo wights files.

  W_IN: integer = 608;
  H_IN: Integer = 608;

  SCALE: Single = 0.00392; -> When I change it to 0.00192, it is similar, but the default is 1.0 and an error occurs.
What does this mean?

**Comment by gidesa** [comment]
Scale is a normalization parameter, as also mean parameter.
Indeed every pixel is changed from a 0-255 value to a 0.0-1.0 float value:
  pf = p * scale - mean
Typically scale = 1 / 255 = 0.00392
So of course you have to EXACTLY match the image normalization used when training.
Have you an example image of the 2 different outputs?

**Comment by hechoel** [comment]
I didn't understand exactly..

Attach image and cfg. 
Can you tell me how to calculate it?
[projectname8.zip](https://github.com/gidesa/ocvWrapper46/files/15462501/projectname8.zip)

**Comment by gidesa** [comment]
Of course you should read the Yolo program documentation for exact parameters description.
But in cfg file I see:
- size 640x640, not 608
- scales= 0.1, 0.1  , not 0.00392
There is no mean parameter, indeed.
You have to see Yolo doc or source to find exact normalization parameters used.

**Comment by gidesa** [comment]
I have found the Yolo normalization algorithm, see image.
The SCALE = 0.00392 is correct. Same for mean, it's all zeros.
So the different output that you see could depend from image size, 640x640 and not 608x608. Of course if the cfg file is the one that you used in Yolo training.
![yolo-normalization](https://github.com/gidesa/ocvWrapper46/assets/22103113/2408d6a3-eec9-4e13-8ead-c0dd429ca642)
