### ISSUE TITLE
Is it possible to add support for other pixel value types, such as `uint16_t`?

### ISSUE THREAD

**Issue by uamhforever** [gidesa/ocvWrapper46#23]
The current pixel value types only support `byte`, `int`, `float`, `double`, and 3-channel types. Is it possible to add support for other types, such as uint16_t? For example, I have a C program call `in_img.at<uint16_t>(r, c)`. How can I change it to a way supported by Free Pascal?

**Comment by gidesa** [comment]
Hello,
depends on C program. It seems that it read an element from a 1-channel matrix, casting to 16bit. But the matrix  indeed could be defined of different type.
You have to verify if that type is  CV_16U1, that is unsigned 16bit 1-channel.

EDIT: you can also convert to a supported type using:

procedure  pCvMatConvertTo(const src: PCvMat_t; const dst: PCvMat_t; dstType: Integer; alpha: Double = 1.0; beta: Double = 0)

in this case you should create a destination matrix with same dimensions of input matrix, and type CV_32SC1 (same for dstType)

**Comment by gidesa** [comment]
Hello, now I am working to add direct support for 16bit values.

**Comment by gidesa** [comment]
Added support for signed 8 bit integer (char in C++, Int8 in Pascal), signed 16bit (short in C++, Smallint in Pascal), unsigned 16bit (ushort in C++, Word in Pascal).

**Comment by uamhforever** [comment]
thank you very much
