### ISSUE TITLE
dnnObjectDetection Hanges

### ISSUE THREAD

**Issue by hafedh-trimeche** [gidesa/ocvWrapper46#3]
Hi,

Please note that dnnObjectDetection (64 bit) hangs at pCvdnn_NetforwardV4(net, vecOut, outNames); instruction

Best regards

**Comment by hafedh-trimeche** [comment]
Downloading files from https://github.com/enazoe/yolo-tensorrt solved the problem

Regards.

**Comment by gidesa** [comment]
Hello,
can you specify what files have downloaded from the link? The net weight and definition?
Anyway, I will test again the 64bit program with the other net files, the ones described in the program source header. 
Thank you

**Comment by hafedh-trimeche** [comment]
Hi,

Please find files used: https://mega.nz/folder/n9QSBSxI#VYxceWYVh6Tok4Aif_l1bg

Best regards.

**Comment by gidesa** [comment]
Hello,
[dnnObjectDetection.zip](https://github.com/gidesa/ocvWrapper46/files/11170551/dnnObjectDetection.zip)

I have compiled the exact source on repository with Delphi 11 64bit (attached the exe). 
It works normally with the net file yolov3.weights, downloaded from https://pjreddie.com/media/files/yolov3.weights.
Have you details on the error?

**Comment by hafedh-trimeche** [comment]
Hello,

Compiled & run without problem.

Regards.
