### ISSUE TITLE
Static vs Dynamic DLL loading

### ISSUE THREAD

**Issue by hafedh-trimeche** [gidesa/ocvWrapper46#5]
Hi,

Please note that when delayed is used for loading DLL an initialization process should only be used after functions/procedures are loaded ; otherwise any attempt to use functions/procedures before DLLs are located (copied to the right location -Directory Path-) will raise an exception.

This code will always fail:

```
initialization
begin
  try
    try
      pCvRedirectException(@cvexception);
    except
      Halt(99);
    end;

      pCvDefaultMat:=pCvMatCreateEmpty();
      pCvDefaultSize:=pCvSizeCreate();
      pCvDefaultPoint:=pCvPointCreate();
      pCvPoint_1_1:=CvPoint_(-1,-1);
      pCvDefaultScalar:=pCvScalarCreate();
      StringEmpty.pstr:=PAnsiChar('');
      pCvStringEmpty:=@StringEmpty;
  except
      begin
          Halt(99);
      end;
  end;

{$IFDEF FPC}
    // For some Opencv functions Freepascal require to set
    // Floating Point Unit exception mask, to disable some exceptions generated
    // from C++
    SetExceptionMask(GetExceptionMask + [exOverflow,exZeroDivide,exInvalidOp]);
{$ENDIF}
```

This initialization section should be invoked once the DLL path was identified.

It would be better to write an initialization procedure to be called after dynamically load DLLs.

```
procedure InitOCVWrapper;
begin
  try
    try
      pCvRedirectException(@cvexception);
    except
      Halt(99);
    end;

      pCvDefaultMat:=pCvMatCreateEmpty();
      pCvDefaultSize:=pCvSizeCreate();
      pCvDefaultPoint:=pCvPointCreate();
      pCvPoint_1_1:=CvPoint_(-1,-1);
      pCvDefaultScalar:=pCvScalarCreate();
      StringEmpty.pstr:=PAnsiChar('');
      pCvStringEmpty:=@StringEmpty;
  except
      begin
          Halt(99);
      end;
  end;

{$IFDEF FPC}
    // For some Opencv functions Freepascal require to set
    // Floating Point Unit exception mask, to disable some exceptions generated
    // from C++
    SetExceptionMask(GetExceptionMask + [exOverflow,exZeroDivide,exInvalidOp]);
{$ENDIF}
end; 

var
  OCVApixxx : procedure(..);cdecl;
  OCVHandle : THandle;

procedure LoadOCVWrapper;
begin
  OCVHandle := LoadLibrary(PChar(ocvWrapper));
  @OCVApixxx := GetProcAddress(OCVHandle,OCVApixxx);
  InitOCVWrapper;
end;

```
So the Delayed condition doesn't help! It's simulated to a static loading method.

Best regards.

**Comment by gidesa** [comment]
Thank you for pointing this.
I understand that calling a Dll function in unit initialization force the Dll load, in an incorrect sequence.
But it seems to me that so Delphi fails to completely address the problem of delayed loading.
The initialization procedure should be automatically called from Delphi only after the Dll is loaded. The
applicative code must not know when loading is activate!  
The "traditional" system of load Dll functions one by one is very unsatisfying for me.
Anyway I will study more on the subject.
Regards

**Comment by gidesa** [comment]
I found that there is the possibility to attach a Delphi hook to Dll load mechanism.
Please test if this solution is working also for you, insert lines at end of OpencvWrapper.pas,
after: function  pCvMorphologyDefaultBordeValue() .....






//----------------------------------------------------------------------------

var
  LoadedRedirectException: Boolean;
  DefaultsVarState: Integer;


procedure InitOCVExcRedirection;
begin
  try
    if not(LoadedRedirectException) then
        LoadedRedirectException:=  pCvRedirectException(@cvexception);
  except
    Halt(99);
  end;
end;


procedure InitOCVDefaults;
begin
  try
     { DefaultsVarState is used for delayed Delphi loading, it avoids
       double calls to create functions}
     if DefaultsVarState<1 then
        begin pCvDefaultMat:=pCvMatCreateEmpty();  Inc(DefaultsVarState); end;
     if DefaultsVarState<2 then
        begin pCvDefaultSize:=pCvSizeCreate();     Inc(DefaultsVarState); end;
     if DefaultsVarState<3 then
        begin pCvDefaultPoint:=pCvPointCreate();   Inc(DefaultsVarState); end;
     if DefaultsVarState<4 then
        begin pCvPoint_1_1:=CvPoint_(-1,-1);       Inc(DefaultsVarState); end;
     if DefaultsVarState<5 then
        begin pCvDefaultScalar:=pCvScalarCreate(); Inc(DefaultsVarState); end;
  except
     begin
          Halt(99);
     end;
  end;
end;


{Only for Delphi on Windows, Dll load notify function}
{$IFDEF MSWINDOWS}
{$IFDEF DELPHIDELAYED}
var
  LOldNotifyHook, LOldFailureHook: TDelayedLoadHook; { for storing the old hook pointers }
function DelayedLoadHook(dliNotify: dliNotification; pdli: PDelayLoadInfo): Pointer; stdcall;
begin
case dliNotify of
    dliNoteEndProcessing:
    begin
      InitOCVExcRedirection;
      InitOCVDefaults;
    end;
    dliFailLoadLibrary:
      WriteLn('Failed to load "', pdli.szDll, '" DLL');
  end;

  { Call the old hooks if they are not nil }
  { This is recommended to do in case the old hook do further processing }
  if dliNotify in [dliFailLoadLibrary, dliFailGetProcAddress] then
  begin
    if Assigned(LOldNotifyHook) then
      LOldFailureHook(dliNotify, pdli);
  end else
  begin
    if Assigned(LOldNotifyHook) then
      LOldNotifyHook(dliNotify, pdli);
  end;

  Result := nil;
end;
{$ENDIF}
{$ENDIF}

{****************************************************************************}
initialization
begin
{$IFDEF DELPHIDELAYED}
{ Install new delayed loading hooks }
  LOldNotifyHook  := SetDliNotifyHook2(DelayedLoadHook);
  LOldFailureHook := SetDliFailureHook2(DelayedLoadHook);
{$ELSE}
  InitOCVExcRedirection;
  InitOCVDefaults;
{$ENDIF}

  StringEmpty.pstr:=PAnsiChar('');
  pCvStringEmpty:=@StringEmpty;

{$IFDEF FPC}
  // For some Opencv functions Freepascal require to set
  // Floating Point Unit exception mask, to disable some exceptions generated
  // from C++
  SetExceptionMask(GetExceptionMask + [exOverflow,exZeroDivide,exInvalidOp]);
{$ENDIF}
end;

{{{{  finalization not changed }}}

**Comment by hafedh-trimeche** [comment]
Hi,

Please find attached units rewritten to handle DLL dynamic loading.
[Delphi.zip](https://github.com/gidesa/ocvWrapper46/files/11413150/Delphi.zip)

Please also note that naming template changed for pCvMatTo**I**plImage:
The **I** of Image is set to Lowercase inside the DLL.
  ```
pCvIplImageToMat := ProcAddress('pCvIplImageToMat');
  pCvMatToIplImage := ProcAddress('pCvMatToIplimage');
  pCvIplImageDelete := ProcAddress('pCvIplImageDelete');
```
Best regards.

**Comment by gidesa** [comment]
It's nice that the wrapper can fulfill your use case,
customized with some work and adjustment.
Regards

**Comment by gidesa** [comment]
Your very useful contribution is now in dyn-loading directory.
Regards

**Comment by hafedh-trimeche** [comment]
Hello,

Please note that dynamic loading would be used by Delphi and FPC. Delay hooking should only be used by Delphi.

Best regards.

**Comment by hafedh-trimeche** [comment]
Hi,

Please note that these units mus be added to **unOpenCVDelphi46**  in case of using Dynamic Loading:
uOcvConst, uOcvTypes, uOcvWrapper and uOcvClasses.

```
interface
uses  Classes, Sysutils,
      {$IFDEF MSWINDOWS} Windows, {$ENDIF}
      {$IFDEF LCL}
      Graphics,
      Types,
      ExtCtrls,
      Generics.Collections,
      {$ELSE}
      Vcl.Graphics,
      Types,
      Vcl.ExtCtrls,
      System.Generics.Collections,
      {$ENDIF}
      uOcvConst,
      uOcvTypes,
      uOcvWrapper,
      uOcvClasses,
      OPENCVWrapper;

```

Best regards.
